ECS-6550 Build key IOC on Rocky 9
pcdshub/ioc-common-ads-ioc pull request #105
Opened 2024-11-23 02:25 UTC by janeliu-slac

config/RELEASE and RELEASE_SITE files have been updated for this IOC.

## Description
config/RELEASE has been updated with the latest EPICS module versions from /cds/group/pcds/epics/R7.0.3.1-2.0/modules/

RELEASE_SITE was updated so `BASE_MODULE_VERSION = R7.0.3.1-2.0`.

## Motivation and Context
Need to build and test IOCs to ensure they run on Rocky 9.

## How Has This Been Tested?
IOCs are tested manually (currently no unit tests exist).
Need to run `make` on this IOC to test that it compiles and is not missing any other settings.

## Where Has This Been Documented?
https://jira.slac.stanford.edu/browse/ECS-6550

2024-11-27 03:40 UTC, ZLLentz requested changes
This IOC builds successfully after the changes, but it has some ignored errors. I suspect it might not run properly.

<details>

```
make -C ./configure install
make[1]: Entering directory '/cds/home/z/zlentz/temp/ioc-common-ads-ioc/configure'
perl -CSD /reg/g/pcds/epics/base/R7.0.3.1-2.0/bin/rhel9-x86_64/makeMakefile.pl O.rhel9-x86_64 ../..
mkdir -p O.Common
make -C O.rhel9-x86_64 -f ../Makefile TOP=../.. \
    T_A=rhel9-x86_64 install
make[2]: Entering directory '/cds/home/z/zlentz/temp/ioc-common-ads-ioc/configure/O.rhel9-x86_64'
perl -CSD /reg/g/pcds/epics/base/R7.0.3.1-2.0/bin/rhel9-x86_64/convertRelease.pl checkRelease

Definition of EPICS_SITE_TOP conflicts with MOTOR support.
In this application or module, a RELEASE file
conflicts with MOTOR at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  MOTOR: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_BASE conflicts with MOTOR support.
In this application or module, a RELEASE file
conflicts with MOTOR at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  Here: EPICS_BASE = /reg/g/pcds/epics//base/R7.0.3.1-2.0
  MOTOR: EPICS_BASE = /cds/group/pcds/epics/base/R7.0.3.1-2.0
Definition of ASYN_MODULE_VERSION conflicts with MOTOR support.
In this application or module, a RELEASE file
conflicts with MOTOR at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  Here: ASYN_MODULE_VERSION = R4.39-1.0.2
  MOTOR: ASYN_MODULE_VERSION = R4.35-0.0.2
Definition of EPICS_MODULES conflicts with MOTOR support.
In this application or module, a RELEASE file
conflicts with MOTOR at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  MOTOR: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of ASYN conflicts with MOTOR support.
In this application or module, a RELEASE file
conflicts with MOTOR at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  Here: ASYN = /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  MOTOR: ASYN = /cds/group/pcds/epics/R7.0.3.1-2.0/modules/asyn/R4.35-0.0.2
Definition of ASYN conflicts with ADS support.
In this application or module, a RELEASE file
conflicts with ADS at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/twincat-ads/R2.0.0-0.0.9
  Here: ASYN = /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  ADS: ASYN = /cds/group/pcds/epics/R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
Definition of EPICS_MODULES conflicts with ADS support.
In this application or module, a RELEASE file
conflicts with ADS at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/twincat-ads/R2.0.0-0.0.9
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  ADS: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of EPICS_BASE conflicts with ADS support.
In this application or module, a RELEASE file
conflicts with ADS at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/twincat-ads/R2.0.0-0.0.9
  Here: EPICS_BASE = /reg/g/pcds/epics//base/R7.0.3.1-2.0
  ADS: EPICS_BASE = /cds/group/pcds/epics/base/R7.0.3.1-2.0
Definition of EPICS_SITE_TOP conflicts with ADS support.
In this application or module, a RELEASE file
conflicts with ADS at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/twincat-ads/R2.0.0-0.0.9
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  ADS: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_MODULES conflicts with ASYN support.
In this application or module, a RELEASE file
conflicts with ASYN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  ASYN: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of EPICS_SITE_TOP conflicts with ASYN support.
In this application or module, a RELEASE file
conflicts with ASYN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  ASYN: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_BASE conflicts with ASYN support.
In this application or module, a RELEASE file
conflicts with ASYN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  Here: EPICS_BASE = /reg/g/pcds/epics//base/R7.0.3.1-2.0
  ASYN: EPICS_BASE = /cds/group/pcds/epics/base/R7.0.3.1-2.0
Definition of EPICS_MODULES conflicts with CAPUTLOG support.
In this application or module, a RELEASE file
conflicts with CAPUTLOG at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/caPutLog/R4.0-1.0.0
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  CAPUTLOG: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of EPICS_SITE_TOP conflicts with CAPUTLOG support.
In this application or module, a RELEASE file
conflicts with CAPUTLOG at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/caPutLog/R4.0-1.0.0
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  CAPUTLOG: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_BASE conflicts with CAPUTLOG support.
In this application or module, a RELEASE file
conflicts with CAPUTLOG at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/caPutLog/R4.0-1.0.0
  Here: EPICS_BASE = /reg/g/pcds/epics//base/R7.0.3.1-2.0
  CAPUTLOG: EPICS_BASE = /cds/group/pcds/epics/base/R7.0.3.1-2.0
Definition of EPICS_MODULES conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  ETHERCATMC: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of ASYN conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: ASYN = /reg/g/pcds/epics//R7.0.3.1-2.0/modules/asyn/R4.39-1.0.2
  ETHERCATMC: ASYN = /cds/group/pcds/epics/R7.0.3.1-2.0/modules/asyn/R4.35-0.0.2
Definition of MOTOR conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: MOTOR = /reg/g/pcds/epics//R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
  ETHERCATMC: MOTOR = /cds/group/pcds/epics/R7.0.3.1-2.0/modules/motor/R6.9-ess-0.0.2
Definition of EPICS_SITE_TOP conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  ETHERCATMC: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_BASE conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: EPICS_BASE = /reg/g/pcds/epics//base/R7.0.3.1-2.0
  ETHERCATMC: EPICS_BASE = /cds/group/pcds/epics/base/R7.0.3.1-2.0
Definition of ASYN_MODULE_VERSION conflicts with ETHERCATMC support.
In this application or module, a RELEASE file
conflicts with ETHERCATMC at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/ethercatmc/R2.1.0-0.1.3
  Here: ASYN_MODULE_VERSION = R4.39-1.0.2
  ETHERCATMC: ASYN_MODULE_VERSION = R4.35-0.0.2
Definition of EPICS_MODULES conflicts with IOCADMIN support.
In this application or module, a RELEASE file
conflicts with IOCADMIN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/iocAdmin/R3.1.16-1.4.0
  Here: EPICS_MODULES = /reg/g/pcds/epics//R7.0.3.1-2.0/modules
  IOCADMIN: EPICS_MODULES = /cds/group/pcds/epics/R7.0.3.1-2.0/modules
Definition of EPICS_SITE_TOP conflicts with IOCADMIN support.
In this application or module, a RELEASE file
conflicts with IOCADMIN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/iocAdmin/R3.1.16-1.4.0
  Here: EPICS_SITE_TOP = /reg/g/pcds/epics/
  IOCADMIN: EPICS_SITE_TOP = /cds/group/pcds/epics
Definition of EPICS_BASE conflicts with IOCADMIN support.
In this application or module, a RELEASE file
conflicts with IOCADMIN at /reg/g/pcds/epics//R7.0.3.1-2.0/modules/iocAdmin/R3.1.16-1.4.0
  Here: EPICS_BA [...]

2024-12-06 19:11 UTC, janeliu-slac commented
I updated EPICS_SITE_TOP and most of the compliation errors have disappeared. There's one last issue related to a dependency with the asyn module. ioc-common-ads-ioc uses ethercatmc/R2.1.0-0.1.3 which has several dependencies like asyn/R4.35-0.0.2 (described in ethercatmc/R2.1.0-0.1.3/RELEASE_NOTES). But ioc-common-ads-ioc also uses twincat-ads/R2.0.0-0.0.9, which depends on asyn/R4.39-1.0.2. I think Jeremy is working out a solution right now.

2024-12-20 19:21 UTC, ZLLentz commented on children/ioc-tst-try-deploy.cfg
> +ENGINEER=Zachary Lentz (zlentz)
Identity theft

2024-12-20 19:22 UTC, ZLLentz commented on children/Makefile
This specific ioc `ioc-common-ads-ioc` doesn't use the RULES_EXPAND so we'll have to test it differently

2024-12-21 00:27 UTC, janeliu-slac commented on children/Makefile
There wasn't a /children folder with .cfg files, so I couldn't mimick another .cfg file to get this to compile. I'll delete this /children folder.

2024-12-21 00:46 UTC, ZLLentz commented on children/Makefile
Yeah, we'll need to do something different, maybe we'll include a PLC project as a submodule or something like that

2025-02-19 01:06 UTC, JJL772 submitted a review, later dismissed

2025-02-19 01:42 UTC, janeliu-slac commented
I think all of the build errors have been resolved and ads-ioc is compiling normally for me. There are some warnings in the C code that also appear in the rhel7 version. I also noticed a new warning:

```
../infoFieldArchive.c:104:13: warning: ‘strncpy’ specified bound 10 equals destination size [-Wstringop-truncation]
  104 |             strncpy(entry->interval_string, token, MAX_INTERVAL_STRING);
```

Seems like this warning was added to GCC 8 (https://stackoverflow.com/questions/50198319/gcc-8-wstringop-truncation-what-is-the-good-practice) and probably would have shown up in rhel7 too. I'm guessing the warning is okay to ignore as long as `token` isn't expected to exceed the value of `MAX_INTERVAL_STRING` on rocky9.

2025-02-19 01:47 UTC, JJL772 commented
-Wstringop-truncation is simultaneously super helpful and super annoying. 

In this case it might be a problem because `strncpy` doesn't always terminate the destination buffer. If token >= `MAX_INTERVAL_STRING`, `entry->interval_string` will not have a null terminator.

Might want to replace it with this:
```cpp
strncpy(entry->interval_string, token, MAX_INTERVAL_STRING-1);
entry->interval_string[MAX_INTERVAL_STRING-1] = 0;
```

2025-02-19 22:39 UTC, JJL772 commented on app/src/infoFieldArchive.c
>              strncpy(entry->interval_string, token, MAX_INTERVAL_STRING);
You might need to change the `MAX_INTERVAL_STRING` to `MAX_INTERVAL_STRING-1` here to suppress the warning. Does GCC still warn here?

2025-02-19 23:31 UTC, janeliu-slac commented on app/src/infoFieldArchive.c
>              strncpy(entry->interval_string, token, MAX_INTERVAL_STRING);
I'm not getting any more gcc warnings for strncpy. I think it might not be necessary to change `MAX_INTERVAL_STRING` to `MAX_INTERVAL_STRING-1`. If string source is bigger than the destination, strncpy is going to overwrite the destination without a null terminator. So, `entry->interval_string[MAX_INTERVAL_STRING - 1] = '\0';` puts the null terminator at the end.

2025-02-19 23:39 UTC, JJL772 commented on app/src/infoFieldArchive.c
>              strncpy(entry->interval_string, token, MAX_INTERVAL_STRING);
GCC is a lot smarter than I thought it was! I wasn't sure if it'd pick up on the termination on the next line.

Thanks for applying this change!

2025-02-19 23:40 UTC, JJL772 approved these changes

2025-02-20 00:10 UTC, janeliu-slac commented
ads-ioc is building without errors on both rhel7 and rocky9. I think it's ready for testing!

2025-02-20 18:18 UTC, ZLLentz commented on app/src/infoFieldArchive.c
> +#define MAX_INTERVAL_STRING 10 // max length of interval string in info value
I notice a lot of whitespace changes in your most recent commits. Is there a code formatter you're using for these?

2025-02-20 18:32 UTC, janeliu-slac commented on app/src/infoFieldArchive.c
> +#define MAX_INTERVAL_STRING 10 // max length of interval string in info value
I use VS Code's C/C++ extension pack (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). 

Shift + Alt + F will format all the code on the page (https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting)

2025-03-18 23:39 UTC, ZLLentz reviewed
I think this one looks good, only gating on hardware testing. Surely we can pick an arbitrary PLC to install at the maker space, this will likely be much easier than other devices.

2025-04-14 18:38 UTC, ZLLentz commented
I fixed the main issue found in hardware testing at https://github.com/pcdshub/twincat-ads/pull/17

So if we merge that and tag again, we can update the ads module reference here and be in a better place.

Other issues I found that we could address in this PR:

- st.cmd generates with the wrong shebang line on rocky9, but launches correctly anyway (???)
- the auto route creation fails with a timeout on rhel7 for a bsd plc (we should just skip this)
- the auto route creation fails with a python exception on rocky9 (import error)
- macro EPICS_CAPUTLOG_HOST is undefined

2025-04-14 20:45 UTC, ZLLentz commented
My intuition is that we should merge this PR once we can update it to the new ADS module tag (once it exists) and then I'm happy to make a follow-up PR for these smaller unrelated items. Otherwise, feel free to search for fixes to these yourself here if motivated.

2025-04-15 20:48 UTC, ZLLentz commented on configure/RELEASE
> +ADS_MODULE_VERSION = R2.0.0-0.0.9
This is the new version now
```suggestion
ADS_MODULE_VERSION = R2.0.0-0.0.10
```

2025-04-16 22:27 UTC, ZLLentz commented on configure/RELEASE
> +ADS_MODULE_VERSION = R2.0.0-0.0.9
@janeliu-slac I want to make this change, merge, and then start looking at the follow-up smaller issues. Is this ok?

2025-04-17 01:06 UTC, janeliu-slac commented on configure/RELEASE
> +ADS_MODULE_VERSION = R2.0.0-0.0.9
Sure, this ADS module version builds correctly for me on rocky9 and rhel7.

2025-04-17 17:17 UTC, ZLLentz approved these changes

2025-04-17 17:17 UTC, merged